export const skills = [
    { id: "1", skill: "Semantic & accessible HTML" },
    { id: "2", skill: "Responsive Web Design" },
    { id: "3", skill: "Teamwork" },
    { id: "4", skill: "Git" },
    { id: "5", skill: "Immutability" },
    { id: "6", skill: "CSS BEM convention" },
    { id: "7", skill: "CSS Grid" },
    { id: "8", skill: "CSS Flexbox" },
    { id: "9", skill: "React" },
    { id: "10", skill: "React Router" },
    { id: "11", skill: "Redux-Saga" },
    { id: "12", skill: "Redux (Toolkit)" },
    { id: "13", skill: "React Hooks" },
    { id: "14", skill: "Error handling" },
    { id: "15", skill: "Working with API (fetch, axios)" },
    { id: "16", skill: "JavaScript: ES6+" },
    { id: "17", skill: "Promises, Async/Await" },
    { id: "18", skill: "GitHub Pull Requests & Review" },
    { id: "19", skill: "Trello" },
    { id: "20", skill: "Scrum" },
    { id: "21", skill: "npm" },
    { id: "22", skill: "GitHub" },
    { id: "23", skill: "Git" },
    { id: "24", skill: "Markdown" },
    { id: "25", skill: "Figma" },
];
